name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install
        run: yarn
      - name: Build
        run: yarn build

  docs:
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Docs
        uses: benc-uk/workflow-dispatch@v1
        with:
          ref: docs
          workflow: Deploy
          repo: koishijs/koishijs.github.io
          token: ${{ secrets.WORKFLOW_TOKEN }}
