name: Build

on:
  - push
  - pull_request

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install
        run: yarn
      - name: Build
        run: yarn build
      - name: Trigger Docs
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Test
          repo: koishijs/koishi
          token: ${{ secrets.WORKFLOW_TOKEN }}
